// <auto-generated />
using System;
using LinksShortening.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LinksShortening.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220813132628_InitailMigration")]
    partial class InitailMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("LinksShortening.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("DATE")
                        .HasColumnName("CreationDate");

                    b.Property<int>("Jumps")
                        .HasColumnType("INT")
                        .HasColumnName("Jumps");

                    b.Property<string>("LongURL")
                        .HasColumnType("TEXT")
                        .HasColumnName("LongURL");

                    b.Property<string>("ShortURL")
                        .HasColumnType("TEXT")
                        .HasColumnName("ShortURL");

                    b.HasKey("Id");

                    b.ToTable("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
